# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[4, 4, 4, 8, 9, 0, 0, 2, 6, 4, 0, 0],
       [1, 4, 2, 6, 4, 9, 6, 1, 6, 5, 8, 5],
       [1, 0, 1, 1, 5, 6, 8, 0, 9, 5, 1, 6],
       [1, 5, 6, 6, 5, 6, 8, 6, 2, 6, 3, 3],
       [5, 1, 6, 4, 3, 2, 9, 5, 8, 1, 3, 4],
       [2, 3, 2, 4, 5, 1, 7, 3, 9, 5, 0, 5],
       [7, 9, 8, 1, 1, 5, 8, 3, 9, 4, 2, 1],
       [2, 8, 5, 4, 9, 8, 0, 3, 7, 6, 1, 0],
       [7, 9, 4, 3, 5, 7, 7, 4, 9, 9, 3, 9],
       [3, 1, 9, 2, 6, 3, 2, 2, 0, 9, 9, 3],
       [9, 1, 5, 6, 1, 6, 8, 9, 3, 9, 5, 7],
       [3, 6, 0, 6, 4, 5, 9, 6, 8, 5, 9, 5]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

C:\Users\IZONE\AppData\Local\Temp/ipykernel_13052/2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[4, 4, 4, 8, 9, 0, 0, 2, 6, 4, 0, 0],
       [1, 4, 2, 6, 4, 9, 6, 1, 6, 5, 8, 5],
       [1, 0, 1, 1, 5, 6, 8, 0, 9, 5, 1, 6],
       [1, 5, 6, 6, 5, 6, 8, 6, 2, 6, 3, 3],
       [5, 1, 6, 4, 3, 2, 9, 5, 8, 1, 3, 4],
       [2, 3, 2, 4, 5, 1, 7, 3, 9, 5, 0, 5],
       [7, 9, 8, 1, 1, 5, 8, 3, 9, 4, 2, 1],
       [2, 8, 5, 4, 9, 8, 0, 3, 7, 6, 1, 0],
       [7, 9, 4, 3, 5, 7, 7, 4, 9, 9, 3, 9],
       [3, 1, 9, 2, 6, 3, 2, 2, 0, 9, 9, 3],
       [9, 1, 5, 6, 1, 6, 8, 9, 3, 9, 5, 7],
       [3, 6, 0, 6, 4, 5, 9, 6, 8, 5, 9, 5]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   9,  -7,   9, -13,  20,   6, -10,   3,  -3,  21,   0],
       [  0, -11,  -5, -14,   4,  -4,  12, -24,  23,  -1, -18,   0],
       [  0,  12,   6,   8,   0,   3,   3,   9, -21,  13,  -1,   0],
       [  0, -15,  11,  -3,  -4, -11,  14,  -6,  15, -18,   4,   0],
       [  0,  -2, -13,   4,  11, -15,   7, -12,  11,   6, -15,   0],
       [  0,  10,  15, -13, -16,   2,  17, -11,  13,  -6,   2,   0],
       [  0,   7,  -4,  -2,  18,  11, -26,  -2,   1,   3,  -7,   0],
       [  0,  16, -10,  -3,  -5,   5,  15,  -5,  16,   9, -16,   0],
       [  0, -18,  24, -16,  13,  -9, -12,  -7, -23,   9,  16,   0],
       [  0, -17,   4,  10, -18,   7,   6,  17, -14,  14, -14,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [19]:
l=1
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [20]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  5., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [21]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [22]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [ ]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()